name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Push to GitHub Packages
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sdil/hasura-firebase-auth-webhook:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

